# Generated by Django 4.1.4 on 2022-12-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=20)),
                ('file_path', models.CharField(max_length=150)),
                ('head_count', models.IntegerField(null=True)),
                ('ratio', models.FloatField(null=True)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
